package com.eshop.model;

import com.eshop.model.base.BaseAgent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Agent extends BaseAgent<Agent> {
	public static final Agent dao = new Agent().dao();
}
