package com.eshop.model;

import com.eshop.model.base.BaseBanner;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Banner extends BaseBanner<Banner> {
	public static final Banner dao = new Banner().dao();
}
