package com.eshop.model;

import java.util.ArrayList;
import java.util.List;

import com.eshop.model.base.BaseBbs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bbs extends BaseBbs<Bbs> {
	public static final Bbs dao = new Bbs().dao();
	List<BbsReturn> reply = null;
	List<Goods> rGoods = null;

	/**
	 * 获取bbs 回复
	 */
	public void getBbsReturns() {
		reply = BbsReturn.dao.find("select shop_bbs_return.*,shop_member.nick,shop_member.img from shop_bbs_return left join shop_member on shop_bbs_return.member=shop_member.guid where bbs_guid=?", get("guid"));
	}

	/**
	 * 获取bbs推荐货品
	 */
	public void getRecommendGoods() {
		if(get("recommend")!=null){
			String[] goodsGuidArray = get("recommend").toString().split(",");
			if (goodsGuidArray.length > 0) {
				rGoods = new ArrayList<>();
				for (String gGuid : goodsGuidArray) {
					rGoods.add(Goods.dao.findFirst("select * from shop_goods where guid=?", gGuid));
				}
			}
		}
	}

	public List<BbsReturn> getReply() {
		return reply;
	}

	public List<Goods> getRGoods() {
		return rGoods;
	}

}
