package com.eshop.model;

import com.eshop.model.base.BaseBbsReturn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BbsReturn extends BaseBbsReturn<BbsReturn> {
	public static final BbsReturn dao = new BbsReturn().dao();
}
