package com.eshop.model;

import com.eshop.model.base.BaseCartItem;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
public class CartItem extends BaseCartItem<CartItem> {
	private static final long serialVersionUID = 540983814622508975L;
	public static final CartItem dao = new CartItem().dao();
	private List<GoodSpec> goodSpecList;
	private Double price;
	private String productGuid;

	public String getProductGuid() {
		return productGuid;
	}

	public void setProductGuid(String productGuid) {
		this.productGuid = productGuid;
	}

	public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public List<GoodSpec> getGoodSpecList() {
		return goodSpecList;
	}

	public void setGoodSpecList(List<GoodSpec> goodSpecList) {
		this.goodSpecList = goodSpecList;
	}

	public List<GoodSpec> findGoodSpec(){
		List<GoodSpec> goodSpecs = new ArrayList<GoodSpec>();
		List<Record> records = Db.find("select * from shop_goods_spec where good_guid = ?",getGoodGuid());
		for(Record record : records){
			GoodSpec goodSpec = new GoodSpec();
			goodSpec.setSpecName(record.getStr("spec_name"));
			goodSpec.setSpecValue(record.getStr("spec_value"));
			goodSpecs.add(goodSpec);
		}
		return goodSpecs;
	}
}
