package com.eshop.model;

import com.eshop.model.base.BaseChoice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Choice extends BaseChoice<Choice> {
	public static final Choice dao = new Choice().dao();
}
