package com.eshop.model;

import java.util.List;

import com.eshop.model.base.BaseClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Clazz extends BaseClass<Clazz> {
	public static final Clazz dao = new Clazz().dao();
	private List<Product> products = null;
	private List<Clazz> subClazzs = null;

	/**
	 * 用当前级别的商品设置products 属性
	 * 
	 */
	public void setProductsWithCurrentClassProducts() {
		products = Product.dao.find("select * from shop_product where pro_class =?", get("guid"));
	}

	/**
	 * 获取子类的列表
	 */
	public void setSubClassWithSql() {
		subClazzs = Clazz.dao.find("select * from shop_class where parent=?", getGuid());
	}

	public List<Clazz> getSubClazzs() {
		return subClazzs;
	}

	public void setSubClazzs(List<Clazz> clazzs) {
		subClazzs = clazzs;
	}

	public List<Product> getProducts() {
		if (null == products) {
			// setProductsWithCurrentClassProducts();
		}
		return products;
	}
}
