package com.eshop.model;

import com.eshop.model.base.BaseEnoughCut;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EnoughCut extends BaseEnoughCut<EnoughCut> {
	public static final EnoughCut dao = new EnoughCut().dao();
}
