package com.eshop.model;

import com.eshop.model.base.BaseGoods;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Goods extends BaseGoods<Goods> {
	public static final Goods dao = new Goods().dao();

	private List<GoodSpec> goodSpecList;

	private Integer quantity;

	public Integer getQuantity() {
		return quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public List<GoodSpec> getGoodSpecList() {
		return goodSpecList;
	}

	public void setGoodSpecList(List<GoodSpec> goodSpecList) {
		this.goodSpecList = goodSpecList;
	}

	public List<GoodSpec> findGoodSpec(){
		List<GoodSpec> goodSpecs = new ArrayList<GoodSpec>();
		List<Record> records = Db.find("select * from shop_goods_spec where good_guid = ?",getGuid());
		for(Record record : records){
			GoodSpec goodSpec = new GoodSpec();
			goodSpec.setSpecName(record.getStr("spec_name"));
			goodSpec.setSpecValue(record.getStr("spec_value"));
			goodSpecs.add(goodSpec);
		}
		return goodSpecs;
	}
}
