package com.eshop.model;

import com.eshop.model.base.BaseGoodEva;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodEva extends BaseGoodEva<GoodEva> {
	public static final GoodEva dao = new GoodEva().dao();
	private Goods goods;
	public Goods getGoods() {
		return goods;
	}
	public void setGoodsBySql() {
		this.goods = Goods.dao.findFirst("select * from shop_goods where guid = ?",getGoodGuid());
	}
	
	
}
