package com.eshop.model;

import com.eshop.model.base.BaseMemberGrade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberGrade extends BaseMemberGrade<MemberGrade> {
	public static final MemberGrade dao = new MemberGrade().dao();
}
