package com.eshop.model;

import com.eshop.model.base.BaseMemberEvalue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberEvalue extends BaseMemberEvalue<MemberEvalue> {
	public static final MemberEvalue dao = new MemberEvalue().dao();
}
