package com.eshop.model;

import com.eshop.model.base.BaseMemberMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberMessage extends BaseMemberMessage<MemberMessage> {
	public static final MemberMessage dao = new MemberMessage().dao();
}
