package com.eshop.model;

import java.util.List;

import com.eshop.model.base.BaseMemberPublish;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberPublish extends BaseMemberPublish<MemberPublish> {
	public static final MemberPublish dao = new MemberPublish().dao();
	private List<MemberReturn> returns;
	private Member memberInfo;

	public List<MemberReturn> getReturns() {
		return returns;
	}

	public void setReturns(List<MemberReturn> returns) {
		this.returns = returns;
	}

	public Member getMemberInfo() {
		return memberInfo;
	}

	public void setMemberInfoBySql() {
		Member local = Member.dao.findFirst("select * from shop_member where guid = ?", getMember());
		if (local != null) {
			this.memberInfo = local;
		}
	}

}
