package com.eshop.model;

import com.eshop.model.base.BaseMemberReturn;
import com.jfinal.kit.StrKit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberReturn extends BaseMemberReturn<MemberReturn> {
	public static final MemberReturn dao = new MemberReturn().dao();
	private MemberPublish publish;
	private Member memberInfo;

	public MemberPublish getPublish() {
		return publish;
	}

	public void setPublish(MemberPublish publish) {
		this.publish = publish;
	}

	public Member getMemberInfo() {
		return memberInfo;
	}

	public void setMemberInfoBySql() {
		if (!StrKit.isBlank(getMember())) {
			Member local = Member.dao.findFirst("select * from shop_member where guid=?", getMember());
			if (local != null) {
				this.memberInfo = local;
			}
		}
	}

}
