package com.eshop.model;

import com.eshop.model.base.BaseMemberWine;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberWine extends BaseMemberWine<MemberWine> {
	public static final MemberWine dao = new MemberWine().dao();
}
