package com.eshop.model;

import com.eshop.model.base.BaseMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Member extends BaseMember<Member> {
	public static final Member dao = new Member().dao();
	private MemberGrade gradeInfo;
	/** 购物车里的条目数 */
	private int cartItemCount;
	
	public int getCartItemCount() {
		return cartItemCount;
	}

	public void setCartItemCount(int cartItemCount) {
		this.cartItemCount = cartItemCount;
	}

	public void setGradeInfoBySql() {
		Integer lGrade;
		if((lGrade=getGrade())!=null&&lGrade>0) {
			gradeInfo=MemberGrade.dao.findFirst("select * from shop_member_grade where grade = ?",lGrade);	
		}
		
	}
	
	public MemberGrade getGradeInfo() {
		return gradeInfo;
	}
	
}
