package com.eshop.model;

import com.eshop.model.base.BaseMemberAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberAddress extends BaseMemberAddress<MemberAddress> {
	public static final MemberAddress dao = new MemberAddress().dao();
}
