package com.eshop.model;

import com.eshop.model.base.BaseOrderItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderItem extends BaseOrderItem<OrderItem> {
	public static final OrderItem dao = new OrderItem().dao();
}
