package com.eshop.model;

import com.eshop.model.base.BaseOrderReturn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderReturn extends BaseOrderReturn<OrderReturn> {
	public static final OrderReturn dao = new OrderReturn().dao();
}
