package com.eshop.model;

import com.eshop.model.base.BaseRun;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Run extends BaseRun<Run> {
	public static final Run dao = new Run().dao();
}
