package com.eshop.model;

import com.eshop.model.base.BaseSpecValue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SpecValue extends BaseSpecValue<SpecValue> {
	public static final SpecValue dao = new SpecValue().dao();
}
