package com.eshop.model;

import com.eshop.model.base.BaseStore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Store extends BaseStore<Store> {
	public static final Store dao = new Store().dao();
}
