package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMemberPublish<M extends BaseMemberPublish<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setGuid(java.lang.String guid) {
		set("guid", guid);
		return (M)this;
	}

	public java.lang.String getGuid() {
		return getStr("guid");
	}

	public M setMember(java.lang.String member) {
		set("member", member);
		return (M)this;
	}

	public java.lang.String getMember() {
		return getStr("member");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setImgs(java.lang.String imgs) {
		set("imgs", imgs);
		return (M)this;
	}

	public java.lang.String getImgs() {
		return getStr("imgs");
	}

	public M setRNum(java.lang.Integer rNum) {
		set("r_num", rNum);
		return (M)this;
	}

	public java.lang.Integer getRNum() {
		return getInt("r_num");
	}

	public M setCNum(java.lang.Integer cNum) {
		set("c_num", cNum);
		return (M)this;
	}

	public java.lang.Integer getCNum() {
		return getInt("c_num");
	}

	public M setGNum(java.lang.Integer gNum) {
		set("g_num", gNum);
		return (M)this;
	}

	public java.lang.Integer getGNum() {
		return getInt("g_num");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.Integer getState() {
		return getInt("state");
	}
	
	
	public M setNick(java.lang.String nick) {
		set("nick", nick);
		return (M)this;
	}

	public java.lang.String getNick() {
		return getStr("nick");
	}
	
	public M setImg(java.lang.String img) {
		set("img", img);
		return (M)this;
	}

	public java.lang.String getImg() {
		return getStr("img");
	}

}
