package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMemberReturn<M extends BaseMemberReturn<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setPublishGuid(java.lang.String publishGuid) {
		set("publish_guid", publishGuid);
		return (M)this;
	}

	public java.lang.String getPublishGuid() {
		return getStr("publish_guid");
	}

	public M setMember(java.lang.String member) {
		set("member", member);
		return (M)this;
	}

	public java.lang.String getMember() {
		return getStr("member");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setIsC(java.lang.Integer isC) {
		set("is_c", isC);
		return (M)this;
	}

	public java.lang.Integer getIsC() {
		return getInt("is_c");
	}

	public M setIsG(java.lang.Integer isG) {
		set("is_g", isG);
		return (M)this;
	}

	public java.lang.Integer getIsG() {
		return getInt("is_g");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	public M setImg(java.lang.String img) {
		set("img", img);
		return (M)this;
	}

	public java.lang.String getImg() {
		return getStr("img");
	}
    
	public M setNick(java.lang.String nick) {
		set("nick", nick);
		return (M)this;
	}

	public java.lang.String getNick() {
		return getStr("nick");
	}
}
