package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLog<M extends BaseLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public M setUserAcc(java.lang.String userAcc) {
		set("user_acc", userAcc);
		return (M)this;
	}

	public java.lang.String getUserAcc() {
		return getStr("user_acc");
	}

	public M setUserBz(java.lang.String userBz) {
		set("user_bz", userBz);
		return (M)this;
	}

	public java.lang.String getUserBz() {
		return getStr("user_bz");
	}

	public M setAKey(java.lang.String aKey) {
		set("a_key", aKey);
		return (M)this;
	}

	public java.lang.String getAKey() {
		return getStr("a_key");
	}

	public M setMethod(java.lang.String method) {
		set("method", method);
		return (M)this;
	}

	public java.lang.String getMethod() {
		return getStr("method");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
