package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCartItem<M extends BaseCartItem<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCartGuid(java.lang.String cartGuid) {
		set("cart_guid", cartGuid);
		return (M)this;
	}

	public java.lang.String getCartGuid() {
		return getStr("cart_guid");
	}

	public M setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
		return (M)this;
	}

	public java.lang.Integer getQuantity() {
		return getInt("quantity");
	}

	public M setGoodGuid(java.lang.String goodGuid) {
		set("good_guid", goodGuid);
		return (M)this;
	}

	public java.lang.String getGoodGuid() {
		return getStr("good_guid");
	}
    
	public M setGoodName(java.lang.String goodName) {
		set("good_name", goodName);
		return (M)this;
	}

	public java.lang.String getGoodName() {
		return getStr("good_name");
	}
	
	public M setImage(java.lang.String image) {
		set("image", image);
		return (M)this;
	}

	public java.lang.String getImage() {
		return getStr("image");
	}
	
	public M setPrdType(java.lang.Integer prdType) {
		set("prd_type", prdType);
		return (M)this;
	}

	public java.lang.Integer getPrdType() {
		return getInt("prd_type");
	}
	
}
