package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSn(java.lang.String sn) {
		set("sn", sn);
		return (M)this;
	}

	public java.lang.String getSn() {
		return getStr("sn");
	}

	public M setPayment(java.lang.String payment) {
		set("payment", payment);
		return (M)this;
	}

	public java.lang.String getPayment() {
		return getStr("payment");
	}

	public M setMember(java.lang.String member) {
		set("member", member);
		return (M)this;
	}

	public java.lang.String getMember() {
		return getStr("member");
	}

	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}

	public java.lang.String getProvince() {
		return getStr("province");
	}

	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}

	public java.lang.String getCity() {
		return getStr("city");
	}

	public M setArea(java.lang.String area) {
		set("area", area);
		return (M)this;
	}

	public java.lang.String getArea() {
		return getStr("area");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}

	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setConsignee(java.lang.String consignee) {
		set("consignee", consignee);
		return (M)this;
	}

	public java.lang.String getConsignee() {
		return getStr("consignee");
	}

	public M setFee(java.lang.Double fee) {
		set("fee", fee);
		return (M)this;
	}

	public java.lang.Double getFee() {
		return getDouble("fee");
	}

	public M setFreight(java.lang.Integer freight) {
		set("freight", freight);
		return (M)this;
	}

	public java.lang.Integer getFreight() {
		return getInt("freight");
	}

	public M setDeliveryTime(java.lang.String deliveryTime) {
		set("delivery_time", deliveryTime);
		return (M)this;
	}

	public java.lang.String getDeliveryTime() {
		return getStr("delivery_time");
	}

	public M setFullCutDeals(java.lang.Integer fullCutDeals) {
		set("full_cut_deals", fullCutDeals);
		return (M)this;
	}

	public java.lang.Integer getFullCutDeals() {
		return getInt("full_cut_deals");
	}

	public M setWine(java.lang.Integer wine) {
		set("wine", wine);
		return (M)this;
	}

	public java.lang.Integer getWine() {
		return getInt("wine");
	}

	public M setIsnee(java.lang.Integer isnee) {
		set("isnee", isnee);
		return (M)this;
	}

	public java.lang.Integer getIsnee() {
		return getInt("isnee");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setIsEnoughCut(java.lang.Integer isEnoughCut) {
		set("is_enough_cut", isEnoughCut);
		return (M)this;
	}

	public java.lang.Integer getIsEnoughCut() {
		return getInt("is_enough_cut");
	}

	public M setOrderStatus(java.lang.Integer orderStatus) {
		set("order_status", orderStatus);
		return (M)this;
	}

	public java.lang.Integer getOrderStatus() {
		return getInt("order_status");
	}

	/**
	 * 
	 * @param payType  支付方式[1:支付宝 2:微信 3:货到付款]
	 * @return
	 */
	public M setPayType(java.lang.Integer payType) {
		set("pay_type", payType);
		return (M)this;
	}

	public java.lang.Integer getPayType() {
		return getInt("pay_type");
	}

	public M setPayStatus(java.lang.Integer payStatus) {
		set("pay_status", payStatus);
		return (M)this;
	}

	public java.lang.Integer getPayStatus() {
		return getInt("pay_status");
	}

	public M setDisStatus(java.lang.Integer disStatus) {
		set("dis_status", disStatus);
		return (M)this;
	}

	public java.lang.Integer getDisStatus() {
		return getInt("dis_status");
	}

	public M setEvaStatus(java.lang.Integer evaStatus) {
		set("eva_status", evaStatus);
		return (M)this;
	}

	public java.lang.Integer getEvaStatus() {
		return getInt("eva_status");
	}

	public M setPayTime(java.util.Date payTime) {
		set("pay_time", payTime);
		return (M)this;
	}

	public java.util.Date getPayTime() {
		return get("pay_time");
	}
	public M setPaySn(java.lang.String paySn) {
		set("pay_sn", paySn);
		return (M)this;
	}

	public java.lang.String getPaySn() {
		return getStr("pay_sn");
	}
	
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setFinishTime(java.util.Date finishTime) {
		set("finish_time", finishTime);
		return (M)this;
	}

	public java.util.Date getFinishTime() {
		return get("finish_time");
	}
	
	public M setOrderType(java.lang.Integer orderType) {
		set("order_type", orderType);
		return (M)this;
	}

	public java.lang.Integer getOrderType() {
		return getInt("order_type");
	}

}
