package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMemberWine<M extends BaseMemberWine<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setIsuse(java.lang.Integer isuse) {
		set("isuse", isuse);
		return (M)this;
	}

	public java.lang.Integer getIsuse() {
		return getInt("isuse");
	}

	public M setMember(java.lang.String member) {
		set("member", member);
		return (M)this;
	}

	public java.lang.String getMember() {
		return getStr("member");
	}

	public M setBz(java.lang.String bz) {
		set("bz", bz);
		return (M)this;
	}

	public java.lang.String getBz() {
		return getStr("bz");
	}

	public M setSurplus(java.lang.Integer surplus) {
		set("surplus", surplus);
		return (M)this;
	}

	public java.lang.Integer getSurplus() {
		return getInt("surplus");
	}

	public M setWine(java.lang.Integer wine) {
		set("wine", wine);
		return (M)this;
	}

	public java.lang.Integer getWine() {
		return getInt("wine");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
