package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStore<M extends BaseStore<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setGuid(java.lang.String guid) {
		set("guid", guid);
		return (M)this;
	}

	public java.lang.String getGuid() {
		return getStr("guid");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setImage(java.lang.String image) {
		set("image", image);
		return (M)this;
	}

	public java.lang.String getImage() {
		return getStr("image");
	}

	public M setImg1(java.lang.String img1) {
		set("img1", img1);
		return (M)this;
	}

	public java.lang.String getImg1() {
		return getStr("img1");
	}

	public M setImg2(java.lang.String img2) {
		set("img2", img2);
		return (M)this;
	}

	public java.lang.String getImg2() {
		return getStr("img2");
	}

	public M setImg3(java.lang.String img3) {
		set("img3", img3);
		return (M)this;
	}

	public java.lang.String getImg3() {
		return getStr("img3");
	}

	public M setFzr(java.lang.String fzr) {
		set("fzr", fzr);
		return (M)this;
	}

	public java.lang.String getFzr() {
		return getStr("fzr");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}

	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setLat(java.lang.String lat) {
		set("lat", lat);
		return (M)this;
	}

	public java.lang.String getLat() {
		return getStr("lat");
	}

	public M setLon(java.lang.String lon) {
		set("lon", lon);
		return (M)this;
	}

	public java.lang.String getLon() {
		return getStr("lon");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
