package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEnoughCut<M extends BaseEnoughCut<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setGuid(java.lang.String guid) {
		set("guid", guid);
		return (M)this;
	}

	public java.lang.String getGuid() {
		return getStr("guid");
	}

	public M setGoodGuids(java.lang.String goodGuids) {
		set("good_guids", goodGuids);
		return (M)this;
	}

	public java.lang.String getGoodGuids() {
		return getStr("good_guids");
	}

	public M setImage(java.lang.String image) {
		set("image", image);
		return (M)this;
	}

	public java.lang.String getImage() {
		return getStr("image");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setIsuse(java.lang.Integer isuse) {
		set("isuse", isuse);
		return (M)this;
	}

	public java.lang.Integer getIsuse() {
		return getInt("isuse");
	}

	public M setEnought(java.lang.Integer enought) {
		set("enought", enought);
		return (M)this;
	}

	public java.lang.Integer getEnought() {
		return getInt("enought");
	}

	public M setCut(java.lang.Integer cut) {
		set("cut", cut);
		return (M)this;
	}

	public java.lang.Integer getCut() {
		return getInt("cut");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setFinishTime(java.util.Date finishTime) {
		set("finish_time", finishTime);
		return (M)this;
	}

	public java.util.Date getFinishTime() {
		return get("finish_time");
	}

}
