package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGoodEva<M extends BaseGoodEva<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setGuid(java.lang.String guid) {
		set("guid", guid);
		return (M)this;
	}

	public java.lang.String getGuid() {
		return getStr("guid");
	}

	public M setGoodGuid(java.lang.String goodGuid) {
		set("good_guid", goodGuid);
		return (M)this;
	}

	public java.lang.String getGoodGuid() {
		return getStr("good_guid");
	}

	public M setMember(java.lang.String member) {
		set("member", member);
		return (M)this;
	}

	public java.lang.String getMember() {
		return getStr("member");
	}

	public M setFirstContent(java.lang.String firstContent) {
		set("first_content", firstContent);
		return (M)this;
	}

	public java.lang.String getFirstContent() {
		return getStr("first_content");
	}

	public M setFirstImg(java.lang.String firstImg) {
		set("first_img", firstImg);
		return (M)this;
	}

	public java.lang.String getFirstImg() {
		return getStr("first_img");
	}

	public M setFirstTime(java.util.Date firstTime) {
		set("first_time", firstTime);
		return (M)this;
	}

	public java.util.Date getFirstTime() {
		return get("first_time");
	}

	public M setSecondContent(java.lang.String secondContent) {
		set("second_content", secondContent);
		return (M)this;
	}

	public java.lang.String getSecondContent() {
		return getStr("second_content");
	}

	public M setSecondImg(java.lang.String secondImg) {
		set("second_img", secondImg);
		return (M)this;
	}

	public java.lang.String getSecondImg() {
		return getStr("second_img");
	}

	public M setSecondTime(java.util.Date secondTime) {
		set("second_time", secondTime);
		return (M)this;
	}

	public java.util.Date getSecondTime() {
		return get("second_time");
	}

	public M setIsuse(java.lang.Integer isuse) {
		set("isuse", isuse);
		return (M)this;
	}

	public java.lang.Integer getIsuse() {
		return getInt("isuse");
	}

	public M setSn(java.lang.String sn) {
		set("sn", sn);
		return (M)this;
	}

	public java.lang.String getSn() {
		return getStr("sn");
	}

}
