package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrderReturn<M extends BaseOrderReturn<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSn(java.lang.String sn) {
		set("sn", sn);
		return (M)this;
	}

	public java.lang.String getSn() {
		return getStr("sn");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setGoodGuid(java.lang.String goodGuid) {
		set("good_guid", goodGuid);
		return (M)this;
	}

	public java.lang.String getGoodGuid() {
		return getStr("good_guid");
	}

	public M setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
		return (M)this;
	}

	public java.lang.Integer getQuantity() {
		return getInt("quantity");
	}

	public M setPrice(java.lang.Double price) {
		set("price", price);
		return (M)this;
	}

	public java.lang.Double getPrice() {
		return getDouble("price");
	}

	public M setResion(java.lang.String resion) {
		set("resion", resion);
		return (M)this;
	}

	public java.lang.String getResion() {
		return getStr("resion");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setUpimage(java.lang.String upimage) {
		set("upimage", upimage);
		return (M)this;
	}

	public java.lang.String getUpimage() {
		return getStr("upimage");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setFinishTime(java.util.Date finishTime) {
		set("finish_time", finishTime);
		return (M)this;
	}

	public java.util.Date getFinishTime() {
		return get("finish_time");
	}

}
