package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMemberGrade<M extends BaseMemberGrade<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setGrade(java.lang.Integer grade) {
		set("grade", grade);
		return (M)this;
	}

	public java.lang.Integer getGrade() {
		return getInt("grade");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setLeft(java.lang.Integer left) {
		set("left", left);
		return (M)this;
	}

	public java.lang.Integer getLeft() {
		return getInt("left");
	}

	public M setRight(java.lang.Integer right) {
		set("right", right);
		return (M)this;
	}

	public java.lang.Integer getRight() {
		return getInt("right");
	}

	public M setFreight(java.lang.Integer freight) {
		set("freight", freight);
		return (M)this;
	}

	public java.lang.Integer getFreight() {
		return getInt("freight");
	}

	public M setNext(java.lang.Integer next) {
		set("next", next);
		return (M)this;
	}

	public java.lang.Integer getNext() {
		return (getInt("next") == null ? -1 : getInt("next"));
	}
	
	public M setLevelIcon(java.lang.String levelIcon) {
		set("level_icon", levelIcon);
		return (M)this;
	}

	public java.lang.String getLevelIcon() {
		return (getStr("level_icon") == null ? "" : getStr("level_icon"));
	}

}
